#joint_state_controller:
#  type: joint_state_controller/JointStateController
#  publish_rate: 250

egm_state_controller:
  type: abb_egm_state_controller/EGMStateController
  publish_rate: 250

# These settings must match:
# - Joint names extracted from the ABB robot controller.
# - The 'yumi_' prefix must match the nickname/identifier,
#   which is set in the corresponding launch file.
joint_position_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - yumi_robl_joint_1
    - yumi_robl_joint_2
    - yumi_robl_joint_3
    - yumi_robl_joint_4
    - yumi_robl_joint_5
    - yumi_robl_joint_6
    - yumi_robl_joint_7
    - yumi_robr_joint_1
    - yumi_robr_joint_2
    - yumi_robr_joint_3
    - yumi_robr_joint_4
    - yumi_robr_joint_5
    - yumi_robr_joint_6
    - yumi_robr_joint_7

#joint_traj_vel_controller_l:
#  type: velocity_controllers/JointTrajectoryController
#  joints:
#    - yumi_robl_joint_1
#    - yumi_robl_joint_2
#    - yumi_robl_joint_7
#    - yumi_robl_joint_3
#    - yumi_robl_joint_4
#    - yumi_robl_joint_5
#    - yumi_robl_joint_6


# Borrowed this from kth yumi pkg
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 500

# Joint Trajectory Position Controlles ----------------------------------------
joint_traj_pos_controller_l:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - yumi_robl_joint_1
    - yumi_robl_joint_2
    - yumi_robl_joint_3
    - yumi_robl_joint_4
    - yumi_robl_joint_5
    - yumi_robl_joint_6
    - yumi_robl_joint_7

joint_traj_pos_controller_r:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - yumi_robr_joint_1
    - yumi_robr_joint_2
    - yumi_robr_joint_3
    - yumi_robr_joint_4
    - yumi_robr_joint_5
    - yumi_robr_joint_6
    - yumi_robr_joint_7

# Joint Trajectory Velocity Controller ----------------------------------------
joint_traj_vel_controller_l:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - yumi_robl_joint_1
    - yumi_robl_joint_2
    - yumi_robl_joint_3
    - yumi_robl_joint_4
    - yumi_robl_joint_5
    - yumi_robl_joint_6
    - yumi_robl_joint_7
  gains:
    yumi_robl_joint_1: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robl_joint_2: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robl_joint_3: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robl_joint_4: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robl_joint_5: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robl_joint_6: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robl_joint_7: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
  constraints:
    goal_time: 1
  stop_trajectory_duration: 0
  velocity_ff:
    yumi_robl_joint_1: 1.0
    yumi_robl_joint_2: 1.0
    yumi_robl_joint_3: 1.0
    yumi_robl_joint_4: 1.0
    yumi_robl_joint_5: 1.0
    yumi_robl_joint_6: 1.0
    yumi_robl_joint_7: 1.0

joint_traj_vel_controller_r:
  type: "velocity_controllers/JointTrajectoryController"
  joints:
    - yumi_robr_joint_1
    - yumi_robr_joint_2
    - yumi_robr_joint_3
    - yumi_robr_joint_4
    - yumi_robr_joint_5
    - yumi_robr_joint_6
    - yumi_robr_joint_7
  gains:
    yumi_robr_joint_1: {p: 1.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robr_joint_2: {p: 2.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robr_joint_3: {p: 2.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robr_joint_4: {p: 2.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robr_joint_5: {p: 2.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robr_joint_6: {p: 2.0,  d: 0, i: 0.00, i_clamp: 0.1}
    yumi_robr_joint_7: {p: 2.0,  d: 0, i: 0.00, i_clamp: 0.1}
  constraints:
    goal_time: 1
  stop_trajectory_duration: 0
  velocity_ff:
    yumi_robr_joint_1: 1.0
    yumi_robr_joint_2: 1.0
    yumi_robr_joint_3: 1.0
    yumi_robr_joint_4: 1.0
    yumi_robr_joint_5: 1.0
    yumi_robr_joint_6: 1.0
    yumi_robr_joint_7: 1.0

